#!/usr/bin/env python3
"""
Merge advisor — synthesizes all PR signals into a single merge recommendation
for the human reviewer.

Runs after AI code review and CI complete. Reads:
  - PR diff (risk indicators: schema changes, auth changes, shared files)
  - WO spec (risk tier, acceptance criteria)
  - CI check statuses (via GitHub API)
  - PR metadata (completeness: migration notes, test plan, WO link)

Posts a structured comment with:
  - Clear ✅ / ⚠️ / ❌ recommendation
  - Signal summary table
  - Specific things to verify by hand
  - Rollback instructions if it breaks

Usage:
    python3 scripts/merge_advisor.py \
        --diff /tmp/pr_diff.txt \
        --output /tmp/advisory.md

Environment:
    ANTHROPIC_API_KEY   required
    PR_TITLE            PR title (used to find WO spec)
    PR_BODY             PR body
    PR_NUMBER           PR number (used to fetch GH check statuses)
    GITHUB_TOKEN        GitHub token for check status API
    GITHUB_REPOSITORY   owner/repo (e.g. dentroio/clarion)
    AI_REVIEW_VERDICT   LGTM | Needs attention | Review required (from ai-review step)
    VERIFIER_VERDICT    All criteria met | Partial | Criteria not met (from verifier step)
    CI_STATUS           success | failure | pending

Exit codes:
    0 — advisory posted (any recommendation level)
    1 — error (non-blocking in CI — merge advisor never blocks the merge itself)
"""

import argparse
import json
import os
import re
import sys
import urllib.request
import urllib.error

MAX_DIFF_LINES = 3000

SYSTEM_PROMPT = """You are a merge advisor for an AI engineering team. Your job is to help
the human reviewer decide whether to merge a pull request.

You receive:
- The PR diff
- Signal summary (CI status, AI review verdict, risk tier, schema changes, etc.)
- The WO acceptance criteria (if found)

Write a concise merge advisory. Be direct — the reviewer is busy. Lead with the
recommendation, then give the signals, then specific checks, then rollback.

RESPONSE FORMAT — return exactly this markdown:

### Merge Advisory

**Recommendation:** ✅ Ready to merge / ⚠️ Review before merging / ❌ Do not merge

> [One sentence explaining the recommendation]

### Signal Summary
| Signal | Status | Notes |
|--------|--------|-------|
[Fill in rows for each signal provided. Use ✅ ⚠️ ❌ icons.]

### What to verify before merging
[Bulleted list of 2-5 specific things the reviewer should check manually.
Be concrete — name files, tables, endpoints. If nothing specific, write "Nothing beyond CI — safe to merge as-is."]

### If this breaks production
[2-4 specific rollback steps. Name the exact commands or actions needed. If the change is easily
reverted with `git revert`, say so. If it touches the DB schema, say what to run.]

---
*Merge advisory generated by AI — final decision is yours.*
"""


# ── Risk signal detection ────────────────────────────────────────────────────

SCHEMA_PATTERNS = [
    r"migrations/", r"adapter\.py", r"CREATE TABLE", r"ALTER TABLE",
    r"migrate_postgresql", r"migrate_neo4j",
]
AUTH_PATTERNS = [
    r"require_role", r"JWTAuth", r"jwt", r"password_hash", r"bcrypt",
    r"RBAC", r"permissions", r"is_active",
]
SHARED_FILE_PATTERNS = [
    r"correlation_engine\.py", r"gateway/main\.py", r"ROUTE_PREFIXES",
    r"docker-compose\.yml", r"Dockerfile",
]
BREAKING_PATTERNS = [
    r'"-\s*\w+.*:.*\w+"',   # removed JSON field (heuristic)
    r"response_model.*Optional",
    r"DROP TABLE", r"DROP COLUMN",
]


def detect_risks(diff: str) -> dict:
    return {
        "schema_change": any(re.search(p, diff, re.IGNORECASE) for p in SCHEMA_PATTERNS),
        "auth_change": any(re.search(p, diff, re.IGNORECASE) for p in AUTH_PATTERNS),
        "shared_file": any(re.search(p, diff, re.IGNORECASE) for p in SHARED_FILE_PATTERNS),
        "potential_breaking": any(re.search(p, diff, re.IGNORECASE) for p in BREAKING_PATTERNS),
        "has_tests": bool(re.search(r"test_|\.test\.|\.spec\.", diff, re.IGNORECASE)),
        "migrations_registered": bool(re.search(r"adapter\.py.*migrate_|from.*migrations.*import", diff)),
    }


def check_pr_completeness(pr_title: str, pr_body: str) -> dict:
    body = pr_body or ""
    return {
        "has_wo_link": bool(re.search(r"WO-\d+", pr_title + body)),
        "has_migration_notes": bool(re.search(r"migrat", body, re.IGNORECASE)),
        "has_test_plan": bool(re.search(r"test plan|make ci-local|pytest|npm test", body, re.IGNORECASE)),
        "has_summary": len(body.strip()) > 100,
        "has_coauthor": "Co-Authored-By" in body,
    }


def find_wo_spec(pr_title: str, search_dir: str = "docs/project_management/work_orders") -> str | None:
    match = re.search(r"WO-(\d+)", pr_title)
    if not match:
        return None
    wo_num = int(match.group(1))
    if not os.path.isdir(search_dir):
        return None
    for fname in os.listdir(search_dir):
        if re.match(rf"WO-{wo_num:03d}-.*\.md", fname):
            return os.path.join(search_dir, fname)
    return None


def extract_risk_tier(wo_spec: str) -> str:
    match = re.search(r"\*\*Risk tier:\*\*\s*(.+)", wo_spec)
    return match.group(1).strip() if match else "Unknown"


def extract_acceptance_criteria(wo_spec: str) -> str:
    match = re.search(r"## Acceptance Criteria\s*\n(.*?)(?=\n## |\Z)", wo_spec, re.DOTALL)
    return match.group(1).strip() if match else ""


def get_ci_status() -> str:
    return os.environ.get("CI_STATUS", "unknown")


def build_signal_summary(diff: str, pr_title: str, pr_body: str, wo_spec: str | None) -> str:
    risks = detect_risks(diff)
    completeness = check_pr_completeness(pr_title, pr_body)
    risk_tier = extract_risk_tier(wo_spec) if wo_spec else "Not found in WO spec"
    ac = extract_acceptance_criteria(wo_spec) if wo_spec else ""

    ai_verdict = os.environ.get("AI_REVIEW_VERDICT", "not run")
    verifier_verdict = os.environ.get("VERIFIER_VERDICT", "not run")
    ci_status = get_ci_status()

    lines = [
        f"Risk tier: {risk_tier}",
        f"CI status: {ci_status}",
        f"AI review verdict: {ai_verdict}",
        f"Verifier verdict: {verifier_verdict}",
        f"Schema / migration changes: {'YES' if risks['schema_change'] else 'no'}",
        f"Auth / RBAC changes: {'YES' if risks['auth_change'] else 'no'}",
        f"Shared infrastructure files: {'YES' if risks['shared_file'] else 'no'}",
        f"Potential breaking changes detected: {'YES' if risks['potential_breaking'] else 'no'}",
        f"Tests added or modified: {'yes' if risks['has_tests'] else 'NO — check coverage'}",
        f"Migration registered in adapter.py: {'yes' if risks['migrations_registered'] else 'n/a (no migrations)' if not risks['schema_change'] else 'NOT DETECTED — verify manually'}",
        f"PR has WO link: {'yes' if completeness['has_wo_link'] else 'NO'}",
        f"PR has migration notes: {'yes' if completeness['has_migration_notes'] else 'n/a' if not risks['schema_change'] else 'NO'}",
        f"PR has test plan: {'yes' if completeness['has_test_plan'] else 'NO'}",
        f"PR body is descriptive: {'yes' if completeness['has_summary'] else 'NO — body is thin'}",
    ]

    if ac:
        lines.append(f"\nAcceptance criteria from WO spec:\n{ac}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--diff", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    pr_title = os.environ.get("PR_TITLE", "")
    pr_body = os.environ.get("PR_BODY", "")

    with open(args.diff) as f:
        diff_lines = f.readlines()

    if len(diff_lines) > MAX_DIFF_LINES:
        diff_text = "".join(diff_lines[:MAX_DIFF_LINES])
        diff_text += f"\n\n[Diff truncated at {MAX_DIFF_LINES} lines]"
    else:
        diff_text = "".join(diff_lines)

    wo_spec_path = find_wo_spec(pr_title)
    wo_spec = None
    if wo_spec_path and os.path.exists(wo_spec_path):
        with open(wo_spec_path) as f:
            wo_spec = f.read()

    signal_summary = build_signal_summary(diff_text, pr_title, pr_body, wo_spec)

    user_content = f"""PR Title: {pr_title}

Signal Summary:
{signal_summary}

PR Diff:
```diff
{diff_text}
```

Write the merge advisory."""

    import anthropic

    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1200,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_content}],
    )

    advisory = message.content[0].text

    with open(args.output, "w") as f:
        f.write(advisory)

    print(f"Merge advisory written to {args.output}")


if __name__ == "__main__":
    main()
